version: '3.8'
services:
  app:
    build: .
    container_name: taichu_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_demo:3306/demo_db_taichu?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=demo
      - SPRING_DATASOURCE_PASSWORD=demo123
      - LOG_PATH=/app/logs
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    networks:
      - taichu_network

networks:
  taichu_network:
    name: taichu_network
    external: true 