version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_OPTS=-Dmaven.repo.local=/root/.m2/repository
      cache_from:
        - maven:3.8-openjdk-11
        - openjdk:11-jdk-slim
    container_name: taichu_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_demo:3306/demo_db_taichu?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=demo
      - SPRING_DATASOURCE_PASSWORD=demo123
      - LOG_PATH=/home/${USER}/logs/taichu-fic
      - ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID}
      - ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET}
    volumes:
      - /data/files:/app/data/files
      - ~/logs/taichu-fic:/home/${USER}/logs/taichu-fic
      - maven-repo:/root/.m2/repository
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    networks:
      - taichu_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: demo_db_taichu
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo123
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./taichubackend-starter/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - taichu_network

networks:
  taichu_network:
    driver: bridge

volumes:
  maven-repo: 