package com.taichu.infra.persistance.model;

public class FicAlgoTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.gmt_create
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.workflow_task_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private Long workflowTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.status
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.task_type
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.algo_task_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private Long algoTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.relevant_id_type
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private String relevantIdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.relevant_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private Long relevantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_algo_task.task_abstract
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    private String taskAbstract;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public FicAlgoTask(Long id, Long gmtCreate, Long workflowTaskId, Byte status, String taskType, Long algoTaskId, String relevantIdType, Long relevantId) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.workflowTaskId = workflowTaskId;
        this.status = status;
        this.taskType = taskType;
        this.algoTaskId = algoTaskId;
        this.relevantIdType = relevantIdType;
        this.relevantId = relevantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public FicAlgoTask(Long id, Long gmtCreate, Long workflowTaskId, Byte status, String taskType, Long algoTaskId, String relevantIdType, Long relevantId, String taskAbstract) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.workflowTaskId = workflowTaskId;
        this.status = status;
        this.taskType = taskType;
        this.algoTaskId = algoTaskId;
        this.relevantIdType = relevantIdType;
        this.relevantId = relevantId;
        this.taskAbstract = taskAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public FicAlgoTask() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.id
     *
     * @return the value of fic_algo_task.id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.id
     *
     * @param id the value for fic_algo_task.id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.gmt_create
     *
     * @return the value of fic_algo_task.gmt_create
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.gmt_create
     *
     * @param gmtCreate the value for fic_algo_task.gmt_create
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.workflow_task_id
     *
     * @return the value of fic_algo_task.workflow_task_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public Long getWorkflowTaskId() {
        return workflowTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.workflow_task_id
     *
     * @param workflowTaskId the value for fic_algo_task.workflow_task_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setWorkflowTaskId(Long workflowTaskId) {
        this.workflowTaskId = workflowTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.status
     *
     * @return the value of fic_algo_task.status
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.status
     *
     * @param status the value for fic_algo_task.status
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.task_type
     *
     * @return the value of fic_algo_task.task_type
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.task_type
     *
     * @param taskType the value for fic_algo_task.task_type
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.algo_task_id
     *
     * @return the value of fic_algo_task.algo_task_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public Long getAlgoTaskId() {
        return algoTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.algo_task_id
     *
     * @param algoTaskId the value for fic_algo_task.algo_task_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setAlgoTaskId(Long algoTaskId) {
        this.algoTaskId = algoTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.relevant_id_type
     *
     * @return the value of fic_algo_task.relevant_id_type
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public String getRelevantIdType() {
        return relevantIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.relevant_id_type
     *
     * @param relevantIdType the value for fic_algo_task.relevant_id_type
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setRelevantIdType(String relevantIdType) {
        this.relevantIdType = relevantIdType == null ? null : relevantIdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.relevant_id
     *
     * @return the value of fic_algo_task.relevant_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public Long getRelevantId() {
        return relevantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.relevant_id
     *
     * @param relevantId the value for fic_algo_task.relevant_id
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setRelevantId(Long relevantId) {
        this.relevantId = relevantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_algo_task.task_abstract
     *
     * @return the value of fic_algo_task.task_abstract
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public String getTaskAbstract() {
        return taskAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_algo_task.task_abstract
     *
     * @param taskAbstract the value for fic_algo_task.task_abstract
     *
     * @mbg.generated Sun Jun 08 23:35:10 CST 2025
     */
    public void setTaskAbstract(String taskAbstract) {
        this.taskAbstract = taskAbstract == null ? null : taskAbstract.trim();
    }
}