package com.taichu.infra.persistance.model;

public class FicResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.relevance_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long relevanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.relevance_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String relevanceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.resource_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.resource_storage_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String resourceStorageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.resource_url
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String resourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_resource.extend_info
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String extendInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicResource(Long id, Long gmtCreate, Byte status, Long relevanceId, String relevanceType, String resourceType, String resourceStorageType, String resourceUrl) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.status = status;
        this.relevanceId = relevanceId;
        this.relevanceType = relevanceType;
        this.resourceType = resourceType;
        this.resourceStorageType = resourceStorageType;
        this.resourceUrl = resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicResource(Long id, Long gmtCreate, Byte status, Long relevanceId, String relevanceType, String resourceType, String resourceStorageType, String resourceUrl, String extendInfo) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.status = status;
        this.relevanceId = relevanceId;
        this.relevanceType = relevanceType;
        this.resourceType = resourceType;
        this.resourceStorageType = resourceStorageType;
        this.resourceUrl = resourceUrl;
        this.extendInfo = extendInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.id
     *
     * @return the value of fic_resource.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.id
     *
     * @param id the value for fic_resource.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.gmt_create
     *
     * @return the value of fic_resource.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.gmt_create
     *
     * @param gmtCreate the value for fic_resource.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.status
     *
     * @return the value of fic_resource.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.status
     *
     * @param status the value for fic_resource.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.relevance_id
     *
     * @return the value of fic_resource.relevance_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getRelevanceId() {
        return relevanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.relevance_id
     *
     * @param relevanceId the value for fic_resource.relevance_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setRelevanceId(Long relevanceId) {
        this.relevanceId = relevanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.relevance_type
     *
     * @return the value of fic_resource.relevance_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getRelevanceType() {
        return relevanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.relevance_type
     *
     * @param relevanceType the value for fic_resource.relevance_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setRelevanceType(String relevanceType) {
        this.relevanceType = relevanceType == null ? null : relevanceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.resource_type
     *
     * @return the value of fic_resource.resource_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.resource_type
     *
     * @param resourceType the value for fic_resource.resource_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.resource_storage_type
     *
     * @return the value of fic_resource.resource_storage_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getResourceStorageType() {
        return resourceStorageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.resource_storage_type
     *
     * @param resourceStorageType the value for fic_resource.resource_storage_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setResourceStorageType(String resourceStorageType) {
        this.resourceStorageType = resourceStorageType == null ? null : resourceStorageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.resource_url
     *
     * @return the value of fic_resource.resource_url
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.resource_url
     *
     * @param resourceUrl the value for fic_resource.resource_url
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_resource.extend_info
     *
     * @return the value of fic_resource.extend_info
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getExtendInfo() {
        return extendInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_resource.extend_info
     *
     * @param extendInfo the value for fic_resource.extend_info
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setExtendInfo(String extendInfo) {
        this.extendInfo = extendInfo == null ? null : extendInfo.trim();
    }
}