package com.taichu.infra.persistance.model;

public class FicRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_role.id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_role.workflow_id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private Long workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_role.gmt_create
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_role.status
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_role.role_name
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_role.description
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_role.prompt
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private String prompt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_role.extend_info
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private String extendInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_role
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public FicRole(Long id, Long workflowId, Long gmtCreate, Byte status, String roleName) {
        this.id = id;
        this.workflowId = workflowId;
        this.gmtCreate = gmtCreate;
        this.status = status;
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_role
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public FicRole(Long id, Long workflowId, Long gmtCreate, Byte status, String roleName, String description, String prompt, String extendInfo) {
        this.id = id;
        this.workflowId = workflowId;
        this.gmtCreate = gmtCreate;
        this.status = status;
        this.roleName = roleName;
        this.description = description;
        this.prompt = prompt;
        this.extendInfo = extendInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_role
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public FicRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_role.id
     *
     * @return the value of fic_role.id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_role.id
     *
     * @param id the value for fic_role.id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_role.workflow_id
     *
     * @return the value of fic_role.workflow_id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public Long getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_role.workflow_id
     *
     * @param workflowId the value for fic_role.workflow_id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setWorkflowId(Long workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_role.gmt_create
     *
     * @return the value of fic_role.gmt_create
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_role.gmt_create
     *
     * @param gmtCreate the value for fic_role.gmt_create
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_role.status
     *
     * @return the value of fic_role.status
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_role.status
     *
     * @param status the value for fic_role.status
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_role.role_name
     *
     * @return the value of fic_role.role_name
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_role.role_name
     *
     * @param roleName the value for fic_role.role_name
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_role.description
     *
     * @return the value of fic_role.description
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_role.description
     *
     * @param description the value for fic_role.description
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_role.prompt
     *
     * @return the value of fic_role.prompt
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_role.prompt
     *
     * @param prompt the value for fic_role.prompt
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setPrompt(String prompt) {
        this.prompt = prompt == null ? null : prompt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_role.extend_info
     *
     * @return the value of fic_role.extend_info
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public String getExtendInfo() {
        return extendInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_role.extend_info
     *
     * @param extendInfo the value for fic_role.extend_info
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setExtendInfo(String extendInfo) {
        this.extendInfo = extendInfo == null ? null : extendInfo.trim();
    }
}