package com.taichu.infra.persistance.model;

public class FicScript {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_script.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_script.workflow_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_script.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_script.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_script.order_index
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long orderIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_script.content
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_script.extend_info
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String extendInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicScript(Long id, Long workflowId, Long gmtCreate, Byte status, Long orderIndex) {
        this.id = id;
        this.workflowId = workflowId;
        this.gmtCreate = gmtCreate;
        this.status = status;
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicScript(Long id, Long workflowId, Long gmtCreate, Byte status, Long orderIndex, String content, String extendInfo) {
        this.id = id;
        this.workflowId = workflowId;
        this.gmtCreate = gmtCreate;
        this.status = status;
        this.orderIndex = orderIndex;
        this.content = content;
        this.extendInfo = extendInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicScript() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_script.id
     *
     * @return the value of fic_script.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_script.id
     *
     * @param id the value for fic_script.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_script.workflow_id
     *
     * @return the value of fic_script.workflow_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_script.workflow_id
     *
     * @param workflowId the value for fic_script.workflow_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setWorkflowId(Long workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_script.gmt_create
     *
     * @return the value of fic_script.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_script.gmt_create
     *
     * @param gmtCreate the value for fic_script.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_script.status
     *
     * @return the value of fic_script.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_script.status
     *
     * @param status the value for fic_script.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_script.order_index
     *
     * @return the value of fic_script.order_index
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_script.order_index
     *
     * @param orderIndex the value for fic_script.order_index
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setOrderIndex(Long orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_script.content
     *
     * @return the value of fic_script.content
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_script.content
     *
     * @param content the value for fic_script.content
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_script.extend_info
     *
     * @return the value of fic_script.extend_info
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getExtendInfo() {
        return extendInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_script.extend_info
     *
     * @param extendInfo the value for fic_script.extend_info
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setExtendInfo(String extendInfo) {
        this.extendInfo = extendInfo == null ? null : extendInfo.trim();
    }
}