package com.taichu.infra.persistance.model;

public class FicTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.workflow_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.task_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.relevance_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long relevanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.relevance_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String relevanceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.algo_task_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private Long algoTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_task.task_abstract
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    private String taskAbstract;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicTask(Long id, Long gmtCreate, Long workflowId, Byte status, String taskType, Long relevanceId, String relevanceType, Long algoTaskId) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.workflowId = workflowId;
        this.status = status;
        this.taskType = taskType;
        this.relevanceId = relevanceId;
        this.relevanceType = relevanceType;
        this.algoTaskId = algoTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicTask(Long id, Long gmtCreate, Long workflowId, Byte status, String taskType, Long relevanceId, String relevanceType, Long algoTaskId, String taskAbstract) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.workflowId = workflowId;
        this.status = status;
        this.taskType = taskType;
        this.relevanceId = relevanceId;
        this.relevanceType = relevanceType;
        this.algoTaskId = algoTaskId;
        this.taskAbstract = taskAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public FicTask() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.id
     *
     * @return the value of fic_task.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.id
     *
     * @param id the value for fic_task.id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.gmt_create
     *
     * @return the value of fic_task.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.gmt_create
     *
     * @param gmtCreate the value for fic_task.gmt_create
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.workflow_id
     *
     * @return the value of fic_task.workflow_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.workflow_id
     *
     * @param workflowId the value for fic_task.workflow_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setWorkflowId(Long workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.status
     *
     * @return the value of fic_task.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.status
     *
     * @param status the value for fic_task.status
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.task_type
     *
     * @return the value of fic_task.task_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.task_type
     *
     * @param taskType the value for fic_task.task_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.relevance_id
     *
     * @return the value of fic_task.relevance_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getRelevanceId() {
        return relevanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.relevance_id
     *
     * @param relevanceId the value for fic_task.relevance_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setRelevanceId(Long relevanceId) {
        this.relevanceId = relevanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.relevance_type
     *
     * @return the value of fic_task.relevance_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getRelevanceType() {
        return relevanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.relevance_type
     *
     * @param relevanceType the value for fic_task.relevance_type
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setRelevanceType(String relevanceType) {
        this.relevanceType = relevanceType == null ? null : relevanceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.algo_task_id
     *
     * @return the value of fic_task.algo_task_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public Long getAlgoTaskId() {
        return algoTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.algo_task_id
     *
     * @param algoTaskId the value for fic_task.algo_task_id
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setAlgoTaskId(Long algoTaskId) {
        this.algoTaskId = algoTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_task.task_abstract
     *
     * @return the value of fic_task.task_abstract
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public String getTaskAbstract() {
        return taskAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_task.task_abstract
     *
     * @param taskAbstract the value for fic_task.task_abstract
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    public void setTaskAbstract(String taskAbstract) {
        this.taskAbstract = taskAbstract == null ? null : taskAbstract.trim();
    }
}