package com.taichu.infra.persistance.model;

public class FicUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_user.id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_user.gmt_create
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_user.phone_number
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public FicUser(Long id, Long gmtCreate, String phoneNumber) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public FicUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_user.id
     *
     * @return the value of fic_user.id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_user.id
     *
     * @param id the value for fic_user.id
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_user.gmt_create
     *
     * @return the value of fic_user.gmt_create
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_user.gmt_create
     *
     * @param gmtCreate the value for fic_user.gmt_create
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_user.phone_number
     *
     * @return the value of fic_user.phone_number
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_user.phone_number
     *
     * @param phoneNumber the value for fic_user.phone_number
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }
}