package com.taichu.infra.persistance.model;

public class FicWorkflowMeta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_meta.id
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_meta.workflow_id
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    private Long workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_meta.style_type
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    private String styleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_meta.story_name
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    private String storyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_meta.story_info
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    private String storyInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_meta.ext_info
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    private String extInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public FicWorkflowMeta(Long id, Long workflowId, String styleType, String storyName, String storyInfo) {
        this.id = id;
        this.workflowId = workflowId;
        this.styleType = styleType;
        this.storyName = storyName;
        this.storyInfo = storyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public FicWorkflowMeta(Long id, Long workflowId, String styleType, String storyName, String storyInfo, String extInfo) {
        this.id = id;
        this.workflowId = workflowId;
        this.styleType = styleType;
        this.storyName = storyName;
        this.storyInfo = storyInfo;
        this.extInfo = extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public FicWorkflowMeta() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_meta.id
     *
     * @return the value of fic_workflow_meta.id
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_meta.id
     *
     * @param id the value for fic_workflow_meta.id
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_meta.workflow_id
     *
     * @return the value of fic_workflow_meta.workflow_id
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public Long getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_meta.workflow_id
     *
     * @param workflowId the value for fic_workflow_meta.workflow_id
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void setWorkflowId(Long workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_meta.style_type
     *
     * @return the value of fic_workflow_meta.style_type
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public String getStyleType() {
        return styleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_meta.style_type
     *
     * @param styleType the value for fic_workflow_meta.style_type
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void setStyleType(String styleType) {
        this.styleType = styleType == null ? null : styleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_meta.story_name
     *
     * @return the value of fic_workflow_meta.story_name
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public String getStoryName() {
        return storyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_meta.story_name
     *
     * @param storyName the value for fic_workflow_meta.story_name
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void setStoryName(String storyName) {
        this.storyName = storyName == null ? null : storyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_meta.story_info
     *
     * @return the value of fic_workflow_meta.story_info
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public String getStoryInfo() {
        return storyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_meta.story_info
     *
     * @param storyInfo the value for fic_workflow_meta.story_info
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void setStoryInfo(String storyInfo) {
        this.storyInfo = storyInfo == null ? null : storyInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_meta.ext_info
     *
     * @return the value of fic_workflow_meta.ext_info
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_meta.ext_info
     *
     * @param extInfo the value for fic_workflow_meta.ext_info
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }
}