package com.taichu.infra.persistance.model;

public class FicWorkflowTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_task.id
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_task.gmt_create
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_task.workflow_id
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    private Long workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_task.status
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_task.task_type
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fic_workflow_task.params
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    private String params;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public FicWorkflowTask(Long id, Long gmtCreate, Long workflowId, Byte status, String taskType, String params) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.workflowId = workflowId;
        this.status = status;
        this.taskType = taskType;
        this.params = params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public FicWorkflowTask() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_task.id
     *
     * @return the value of fic_workflow_task.id
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_task.id
     *
     * @param id the value for fic_workflow_task.id
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_task.gmt_create
     *
     * @return the value of fic_workflow_task.gmt_create
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_task.gmt_create
     *
     * @param gmtCreate the value for fic_workflow_task.gmt_create
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_task.workflow_id
     *
     * @return the value of fic_workflow_task.workflow_id
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public Long getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_task.workflow_id
     *
     * @param workflowId the value for fic_workflow_task.workflow_id
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public void setWorkflowId(Long workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_task.status
     *
     * @return the value of fic_workflow_task.status
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_task.status
     *
     * @param status the value for fic_workflow_task.status
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_task.task_type
     *
     * @return the value of fic_workflow_task.task_type
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_task.task_type
     *
     * @param taskType the value for fic_workflow_task.task_type
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fic_workflow_task.params
     *
     * @return the value of fic_workflow_task.params
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fic_workflow_task.params
     *
     * @param params the value for fic_workflow_task.params
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }
}