package com.taichu.infra.persistance.model;

import java.util.ArrayList;
import java.util.List;

public class FicWorkflowMetaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public FicWorkflowMetaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdIsNull() {
            addCriterion("workflow_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdIsNotNull() {
            addCriterion("workflow_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdEqualTo(Long value) {
            addCriterion("workflow_id =", value, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdNotEqualTo(Long value) {
            addCriterion("workflow_id <>", value, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdGreaterThan(Long value) {
            addCriterion("workflow_id >", value, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdGreaterThanOrEqualTo(Long value) {
            addCriterion("workflow_id >=", value, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdLessThan(Long value) {
            addCriterion("workflow_id <", value, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdLessThanOrEqualTo(Long value) {
            addCriterion("workflow_id <=", value, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdIn(List<Long> values) {
            addCriterion("workflow_id in", values, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdNotIn(List<Long> values) {
            addCriterion("workflow_id not in", values, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdBetween(Long value1, Long value2) {
            addCriterion("workflow_id between", value1, value2, "workflowId");
            return (Criteria) this;
        }

        public Criteria andWorkflowIdNotBetween(Long value1, Long value2) {
            addCriterion("workflow_id not between", value1, value2, "workflowId");
            return (Criteria) this;
        }

        public Criteria andStyleTypeIsNull() {
            addCriterion("style_type is null");
            return (Criteria) this;
        }

        public Criteria andStyleTypeIsNotNull() {
            addCriterion("style_type is not null");
            return (Criteria) this;
        }

        public Criteria andStyleTypeEqualTo(String value) {
            addCriterion("style_type =", value, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeNotEqualTo(String value) {
            addCriterion("style_type <>", value, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeGreaterThan(String value) {
            addCriterion("style_type >", value, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("style_type >=", value, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeLessThan(String value) {
            addCriterion("style_type <", value, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeLessThanOrEqualTo(String value) {
            addCriterion("style_type <=", value, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeLike(String value) {
            addCriterion("style_type like", value, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeNotLike(String value) {
            addCriterion("style_type not like", value, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeIn(List<String> values) {
            addCriterion("style_type in", values, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeNotIn(List<String> values) {
            addCriterion("style_type not in", values, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeBetween(String value1, String value2) {
            addCriterion("style_type between", value1, value2, "styleType");
            return (Criteria) this;
        }

        public Criteria andStyleTypeNotBetween(String value1, String value2) {
            addCriterion("style_type not between", value1, value2, "styleType");
            return (Criteria) this;
        }

        public Criteria andStoryNameIsNull() {
            addCriterion("story_name is null");
            return (Criteria) this;
        }

        public Criteria andStoryNameIsNotNull() {
            addCriterion("story_name is not null");
            return (Criteria) this;
        }

        public Criteria andStoryNameEqualTo(String value) {
            addCriterion("story_name =", value, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameNotEqualTo(String value) {
            addCriterion("story_name <>", value, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameGreaterThan(String value) {
            addCriterion("story_name >", value, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("story_name >=", value, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameLessThan(String value) {
            addCriterion("story_name <", value, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameLessThanOrEqualTo(String value) {
            addCriterion("story_name <=", value, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameLike(String value) {
            addCriterion("story_name like", value, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameNotLike(String value) {
            addCriterion("story_name not like", value, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameIn(List<String> values) {
            addCriterion("story_name in", values, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameNotIn(List<String> values) {
            addCriterion("story_name not in", values, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameBetween(String value1, String value2) {
            addCriterion("story_name between", value1, value2, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryNameNotBetween(String value1, String value2) {
            addCriterion("story_name not between", value1, value2, "storyName");
            return (Criteria) this;
        }

        public Criteria andStoryInfoIsNull() {
            addCriterion("story_info is null");
            return (Criteria) this;
        }

        public Criteria andStoryInfoIsNotNull() {
            addCriterion("story_info is not null");
            return (Criteria) this;
        }

        public Criteria andStoryInfoEqualTo(String value) {
            addCriterion("story_info =", value, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoNotEqualTo(String value) {
            addCriterion("story_info <>", value, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoGreaterThan(String value) {
            addCriterion("story_info >", value, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoGreaterThanOrEqualTo(String value) {
            addCriterion("story_info >=", value, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoLessThan(String value) {
            addCriterion("story_info <", value, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoLessThanOrEqualTo(String value) {
            addCriterion("story_info <=", value, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoLike(String value) {
            addCriterion("story_info like", value, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoNotLike(String value) {
            addCriterion("story_info not like", value, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoIn(List<String> values) {
            addCriterion("story_info in", values, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoNotIn(List<String> values) {
            addCriterion("story_info not in", values, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoBetween(String value1, String value2) {
            addCriterion("story_info between", value1, value2, "storyInfo");
            return (Criteria) this;
        }

        public Criteria andStoryInfoNotBetween(String value1, String value2) {
            addCriterion("story_info not between", value1, value2, "storyInfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 21 15:05:51 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fic_workflow_meta
     *
     * @mbg.generated Sat Jun 21 15:05:51 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}