spring:
  application:
    name: taichu-backend
  datasource:
    url: jdbc:mysql://mysql_demo:3306/demo_db_taichu?useSSL=false&serverTimezone=UTC
    username: demo
    password: demo123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://mysql_demo:3306/demo_db_taichu?useSSL=false&serverTimezone=UTC
    user: demo
    password: demo123
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB
      location: /tmp
      resolve-lazily: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

file:
  storage:
    base-path: /app/data/files
    max-size: 20MB
    allowed-types: text/plain,application/pdf
    allow-overwrite: false
    naming-strategy: original

algo:
  service:
    base-url: http://algo-service:8080  # Docker 网络中的算法服务地址

# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucketName: taich-fic-backend-file-storage 