spring:
  application:
    name: taichu-backend
  datasource:
    url: jdbc:mysql://mysql_demo:3306/demo_db_taichu?useSSL=false&serverTimezone=UTC
    username: demo
    password: demo123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://mysql_demo:3306/demo_db_taichu?useSSL=false&serverTimezone=UTC
    user: demo
    password: demo123

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

file:
  storage:
    # 文件存储基础路径
    base-path: /app/data/files
    # 单个文件大小限制
    max-size: 20MB
    # 允许的文件类型
    allowed-types: text/plain,application/pdf
    # 是否允许覆盖已存在的文件
    allow-overwrite: false
    # 文件命名策略：original-保持原文件名，uuid-使用UUID命名
    naming-strategy: original

algo:
  service:
    base-url: http://algo-service:8080  # 算法服务的基础URL，使用Docker服务名

# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com  # OSS 访问域名
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}    # 从环境变量读取
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}  # 从环境变量读取
    bucketName: taich-fic-backend-file-storage  # OSS 存储空间名称 