file:
  storage:
    # 文件存储基础路径
    base-path: /data/files
    # 单个文件大小限制
    max-size: 20MB
    # 允许的文件类型
    allowed-types: text/plain,application/pdf
    # 是否允许覆盖已存在的文件
    allow-overwrite: false
    # 文件命名策略：original-保持原文件名，uuid-使用UUID命名
    naming-strategy: original 

algo:
  service:
    base-url: http://localhost:8080  # 算法服务的基础URL，根据实际环境修改

spring:
  application:
    name: taichu-backend
  flyway:
    enabled: false  # 禁用 Flyway

# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com  # OSS 访问域名
    accessKeyId: your-access-key-id         # 访问密钥 ID
    accessKeySecret: your-access-key-secret # 访问密钥密码
    bucketName: your-bucket-name            # OSS 存储空间名称 