package com.taichu.infra.persistance.mapper;

import com.taichu.infra.persistance.model.FicAlgoTask;
import com.taichu.infra.persistance.model.FicAlgoTaskExample;
import java.util.List;

public interface FicAlgoTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    long countByExample(FicAlgoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    int deleteByExample(FicAlgoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    int insert(FicAlgoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    int insertSelective(FicAlgoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    List<FicAlgoTask> selectByExample(FicAlgoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    FicAlgoTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    int updateByPrimaryKeySelective(FicAlgoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_algo_task
     *
     * @mbg.generated Sat Jun 14 19:02:20 CST 2025
     */
    int updateByPrimaryKey(FicAlgoTask record);
}