package com.taichu.infra.persistance.mapper;

import com.taichu.infra.persistance.model.FicResource;
import com.taichu.infra.persistance.model.FicResourceExample;
import java.util.List;

public interface FicResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    long countByExample(FicResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int deleteByExample(FicResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int insert(FicResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int insertSelective(FicResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    List<FicResource> selectByExampleWithBLOBs(FicResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    List<FicResource> selectByExample(FicResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    FicResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKeySelective(FicResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(FicResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_resource
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKey(FicResource record);
}