package com.taichu.infra.persistance.mapper;

import com.taichu.infra.persistance.model.FicScript;
import com.taichu.infra.persistance.model.FicScriptExample;
import java.util.List;

public interface FicScriptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    long countByExample(FicScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int deleteByExample(FicScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int insert(FicScript record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int insertSelective(FicScript record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    List<FicScript> selectByExampleWithBLOBs(FicScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    List<FicScript> selectByExample(FicScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    FicScript selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKeySelective(FicScript record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(FicScript record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_script
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKey(FicScript record);
}