package com.taichu.infra.persistance.mapper;

import com.taichu.infra.persistance.model.FicTask;
import com.taichu.infra.persistance.model.FicTaskExample;
import java.util.List;

public interface FicTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    long countByExample(FicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int deleteByExample(FicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int insert(FicTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int insertSelective(FicTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    List<FicTask> selectByExampleWithBLOBs(FicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    List<FicTask> selectByExample(FicTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    FicTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKeySelective(FicTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(FicTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_task
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKey(FicTask record);
}