package com.taichu.infra.persistance.mapper;

import com.taichu.infra.persistance.model.FicUser;
import com.taichu.infra.persistance.model.FicUserExample;
import java.util.List;

public interface FicUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    long countByExample(FicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    int deleteByExample(FicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    int insert(FicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    int insertSelective(FicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    List<FicUser> selectByExample(FicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    FicUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    int updateByPrimaryKeySelective(FicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_user
     *
     * @mbg.generated Wed May 07 22:33:14 CST 2025
     */
    int updateByPrimaryKey(FicUser record);
}