package com.taichu.infra.persistance.mapper;

import com.taichu.infra.persistance.model.FicWorkflow;
import com.taichu.infra.persistance.model.FicWorkflowExample;
import java.util.List;

public interface FicWorkflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    long countByExample(FicWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int deleteByExample(FicWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int insert(FicWorkflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int insertSelective(FicWorkflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    List<FicWorkflow> selectByExampleWithBLOBs(FicWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    List<FicWorkflow> selectByExample(FicWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    FicWorkflow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKeySelective(FicWorkflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(FicWorkflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow
     *
     * @mbg.generated Sun May 18 17:57:33 CST 2025
     */
    int updateByPrimaryKey(FicWorkflow record);
}