package com.taichu.infra.persistance.mapper;

import com.taichu.infra.persistance.model.FicWorkflowTask;
import com.taichu.infra.persistance.model.FicWorkflowTaskExample;
import java.util.List;

public interface FicWorkflowTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    long countByExample(FicWorkflowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    int deleteByExample(FicWorkflowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    int insert(FicWorkflowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    int insertSelective(FicWorkflowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    List<FicWorkflowTask> selectByExample(FicWorkflowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    FicWorkflowTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    int updateByPrimaryKeySelective(FicWorkflowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fic_workflow_task
     *
     * @mbg.generated Wed Jun 04 23:17:33 CST 2025
     */
    int updateByPrimaryKey(FicWorkflowTask record);
}